#!/bin/bash

name="$1"

if [ $name == "" ]; then echo "change-default-wallpaper <name>"; exit; fi

cp "~/.dotfiles/wallpapers/${name}.jpg" "~/.dotfiles/wallpapers/default.jpg"

feh --bg-scale "~/.dotfiles/wallpapers/default.jpg"