#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "change-default-wallpaper <name>"
  exit
fi

name="$1"

cp "$HOME/.dotfiles/wallpapers/${name}.jpg" "$HOME/.dotfiles/wallpapers/default.jpg"

feh --bg-scale "$HOME/.dotfiles/wallpapers/default.jpg"