#!/bin/bash

if [ "$#" -ne 1 ]; then
  echo "change-default-wallpaper <name>"
  exit
fi

name="$1"

cp "~/.dotfiles/wallpapers/${name}.jpg" "~/.dotfiles/wallpapers/default.jpg"

feh --bg-scale "~/.dotfiles/wallpapers/default.jpg"